-- Drop and recreate all tables

DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;


CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price INTEGER  NOT NULL,
  picture_url VARCHAR(255) NOT NULL,
  active BOOLEAN
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  type TINYINT NOT NULL,
  email VARCHAR(255),
  phone INTEGER NOT NULL,
  active BOOLEAN
);

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP,
  status VARCHAR(255),
  total_price INTEGER,
  wait_time VARCHAR(255)
)

CREATE TABLE order_items (
  id SERIAL PRIMARY KEY NOT NULL,
  item_id INTEGER REFERENCES items(id) ON DELETE CASCADE,
  qty INTEGER,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE
)
